# Generated by Django 5.2.8 on 2025-11-11 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cart_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=10)),
                ('alternate_no', models.CharField(max_length=10)),
                ('plot_no', models.TextField()),
                ('streetaddress', models.TextField()),
                ('city', models.CharField()),
                ('pincode', models.PositiveBigIntegerField(max_length=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
        ),
    ]
