# Generated by Django 5.2.8 on 2025-11-11 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='pincode',
            field=models.PositiveBigIntegerField(),
        ),
    ]
